export type UserRole = 'Admin' | 'Commandant' | 'Director' | 'Receptionist' | 'Security' | 'Host Employee' | 'PA_TO_DIRECTOR' | 'PA_TO_CI'

export interface UserWithRole {
  id: string
  email: string
  full_name: string | null
  role: UserRole
  created_at: string | null
  must_change_password?: boolean
}

export const PERMISSIONS: Record<UserRole, string[]> = {
  Admin: [
    'dashboard',
    'visitors',
    'visits',
    'employees',
    'reports',
    'audit-logs',
    'scanner',
    'settings',
    'users',
    'delete-records',
    'export-reports',
    'emergency',
    'vehicles',
    'watchlist',
    'documents',
    'analytics',
    'host',
    'email',
    'badges',
    'invitations',
    'operations',
  ],
  Commandant: [
    'dashboard',
    'analytics',
    'reports',
    'audit-logs',
    'visitors',
    'visits',
    'badges',
    'documents',
    'security',
    'host',
    'settings',
    'operations',
  ],
  Director: [
    'dashboard',
    'analytics',
    'reports',
    'audit-logs',
    'visitors',
    'visits',
    'badges',
    'documents',
    'security',
    'host',
    'settings',
    'operations',
  ],
  Receptionist: [
    'dashboard',
    'visitors',
    'visits',
    'scanner',
    'documents',
    'badges',
    'host',
    'invitations',
  ],
  Security: [
    'dashboard',
    'scanner',
    'emergency',
    'vehicles',
    'watchlist',
    'documents',
    'analytics',
    'host',
    'badges',
    'invitations',
    'operations',
  ],
  'Host Employee': [
    'dashboard',
    'view-visitors',
    'view-visits',
    'host',
    'badges',
    'view-today-visits',
    'view-visit-history',
    'invitations',
  ],
  PA_TO_DIRECTOR: [
    'dashboard',
    'visitors',
    'visits',
    'badges',
    'check-in',
    'check-out',
    'documents',
    'host',
  ],
  PA_TO_CI: [
    'dashboard',
    'visitors',
    'visits',
    'badges',
    'check-in',
    'check-out',
    'documents',
    'host',
  ],
}
